### ISSUE TITLE
have_run not operating as expected

### ISSUE THREAD

**Issue by kuleszaj** [technicalpickles/capistrano-spec#11]
Hello,

I'm trying to test a simple capistrano task which runs a command on the local system.

My task looks like:

```
namespace :simple_test do
  desc "testing"
  task :echo do
    system("echo 'test'")
  end
end
```

My test looks like:

```
it "should echo" do
  @configuration.find_and_execute_task("simple_test:echo")
  @configuration.should have_run("echo 'test'")
end
```

But it doesn't seem to be working correctly:

```
Failure/Error: @configuration.should have_run("echo 'test'")
    expected configuration to run echo 'test', but did not
# ./spec/features/deploy_spec.rb:43:in `block (2 levels) in <top (required)>'
```

I've written several other simple tests (such as checking variable values, etc.) which are working fine.

Is there something obvious that I'm missing?

Is there a passing test for "have_run" that positively detects the execution of a command? I notice that all of the current tests for "have_run" here are negative ones: https://github.com/technicalpickles/capistrano-spec/blob/master/spec/capistrano-spec_spec.rb

I'd appreciate any guidance.

Thanks!

**Comment by jgraichen** [comment]
`have_run` can only be used to test remote command. There is currently no way for testing local commands as this would require to mock ruby interpreter calls (`system`, backtick-operator, `%x` and some more) and is unrelated to capistrano. But it may be a nice addition as many recipes are also using local commands...

**Comment by kuleszaj** [comment]
Ah, I missed that about `have_run`. Thank you very much for the quick response. I'll figure out a different way to mock the `system` calls directly.

Thanks!

**Comment by technicalpickles** [comment]
I've found it useful to move system calls  into their own systems, then use rspec's mock/stubs on that method. Quick googling for 'rspec stub system' shows similar recommendations.
