### ISSUE TITLE
Drop Ruby 1.8.7 compatibility

### ISSUE THREAD

**Issue by jhbabon** [technicalpickles/capistrano-spec#15]
As you know, [Ruby 1.8.7 is officially dead](http://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) so maybe is time to drop the support for this version.

For me that means:
- Remove that Ruby version from the [travis config file](https://github.com/technicalpickles/capistrano-spec/blob/master/.travis.yml#L5)
- Use some idioms from 1.9 and 2.0, like hash syntax and fixed methods like `Hash#select` (which returns a hash, not an Array, for example).
- Warn about the change in the README.

What do you thing?

**Comment by technicalpickles** [comment]
Just because it's officially dead, doesn't mean people aren't using it :laughing:

I'd say keep 1.8.7 support until it's problematic to maintain, or blocking other things.

**Comment by petems** [comment]
I agree with @technicalpickles, it's not causing any issues to keep supporting it for now, so I think we should leave it :+1:

**Comment by jhbabon** [comment]
I see another gems dropping the support of version 1.8.7, but your reasons sound good to me, so I close the issue.
